name: web_socket_counter
description: An example counter app built with Dart Frog using WebSockets.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0

dev_dependencies:
  bloc_test: ^9.1.5
  http: ^1.1.0
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
  web_socket_client: ^0.1.0
